[package]
name = "rust-cni"
version = "0.1.2"
edition = "2021"
authors = ["jokemanfire <hu.dingyang@zte.com.cn>"]
description = "a simple cni interface implement by rust" 
keywords = ["network", "cni"]
repository = "https://github.com/jokemanfire/rust-cni"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dev-dependencies]
once_cell = "1.19.0" 

[dependencies]
ipnetwork = "0.17.0"
thiserror = "1.0.20"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
typetag = "0.1.5"
json= "0.12.4"
log = {version = "0.4.2", features=["kv_unstable"]}
env_logger = "0.11.6"
uuid = {version = "1.0", features = ["v4"]} 